/**
 * A minimal pack that passes all seventeen §4.6 rules, so a validator test can
 * break exactly one thing and assert exactly one rule fires.
 *
 * Two activities, so the hue ring step is 180°. `beta` is gated, which is what
 * exercises the three §4.6 additions.
 */

import type { ContentPack } from '../types';

export function minimalPack(): ContentPack {
  return structuredClone(MINIMAL);
}

const MINIMAL: ContentPack = {
  version: 'test',
  activities: [
    {
      id: 'alpha',
      label: 'act.alpha',
      hue: 0,
      order: 0,
      fallbackHours: { wd: 1, we: 1 },
    },
    {
      id: 'beta',
      label: 'act.beta',
      hue: 180,
      order: 1,
      gateField: 'beta.any',
      gateSkipValue: 'no',
      fallbackHours: { wd: 2, we: 2 },
    },
  ],
  screens: [
    {
      id: 'alpha.time',
      sectionId: 'alpha',
      prompt: 'q.alpha.prompt',
      fields: [
        {
          id: 'alpha.minutes.wd',
          label: 'q.day.wd',
          type: 'duration',
          dayType: 'wd',
          unit: 'minutes',
          required: true,
          default: 60,
        },
        {
          id: 'alpha.minutes.we',
          label: 'q.day.we',
          type: 'duration',
          dayType: 'we',
          unit: 'minutes',
          required: true,
          default: 120,
        },
      ],
    },
    {
      id: 'beta.gate',
      sectionId: 'beta',
      prompt: 'q.beta.gate.prompt',
      gate: true,
      fields: [
        {
          id: 'beta.any',
          label: 'q.beta.gate.label',
          type: 'choice',
          required: true,
          default: 'yes',
          options: [
            { id: 'yes', label: 'opt.yes' },
            { id: 'no', label: 'opt.no' },
          ],
        },
      ],
    },
    {
      id: 'beta.time',
      sectionId: 'beta',
      prompt: 'q.beta.time.prompt',
      fields: [
        {
          id: 'beta.minutes.wd',
          label: 'q.day.wd',
          type: 'duration',
          dayType: 'wd',
          unit: 'minutes',
          required: true,
          default: 30,
        },
        {
          id: 'beta.minutes.we',
          label: 'q.day.we',
          type: 'duration',
          dayType: 'we',
          unit: 'minutes',
          required: true,
          default: 30,
        },
      ],
    },
  ],
  estimators: [
    {
      id: 'arith.freqDuration',
      activityId: 'alpha',
      inputs: ['alpha.minutes.wd', 'alpha.minutes.we'],
      outputs: ['wd', 'we'],
      params: {
        terms: [
          { kind: 'duration', field: 'alpha.minutes.wd', dayType: 'wd' },
          { kind: 'duration', field: 'alpha.minutes.we', dayType: 'we' },
        ],
      },
    },
    {
      id: 'arith.freqDuration',
      activityId: 'beta',
      inputs: ['beta.minutes.wd', 'beta.minutes.we'],
      outputs: ['wd', 'we'],
      params: {
        terms: [
          { kind: 'duration', field: 'beta.minutes.wd', dayType: 'wd' },
          { kind: 'duration', field: 'beta.minutes.we', dayType: 'we' },
        ],
      },
    },
  ],
  energy: {
    prompt: 'energy.prompt',
    note: 'energy.note',
    scale: [
      { value: -2, label: 'energy.level.-2' },
      { value: -1, label: 'energy.level.-1' },
      { value: 0, label: 'energy.level.0' },
      { value: 1, label: 'energy.level.1' },
      { value: 2, label: 'energy.level.2' },
    ],
  },
  copy: {
    'act.alpha': 'Alpha',
    'act.beta': 'Beta',
    'q.alpha.prompt': 'How long does alpha take?',
    'q.beta.gate.prompt': 'Do you do beta?',
    'q.beta.gate.label': 'Beta',
    'q.beta.time.prompt': 'How long does beta take?',
    'q.day.wd': 'On a workday',
    'q.day.we': 'On a weekend day',
    'opt.yes': 'Yes',
    'opt.no': 'No',
    's1.progress': '{current} of {total}',
    's2.finish': 'Finish',
    'toggle.wd': 'Work day',
    'toggle.we': 'Weekend',
    'toggle.hours': '{hours} hr',
    's3.title': 'Working through your answers',
    's3.lines.0': 'One',
    's3.lines.1': 'Two',
    's3.lines.2': 'Three',
    's3.lines.3': 'Four',
    'energy.prompt': 'Does each one drain you or give you energy?',
    'energy.note': 'One answer each, for the whole week.',
    'energy.level.-2': 'Drains me a lot',
    'energy.level.-1': 'Drains me a little',
    'energy.level.0': 'Neither',
    'energy.level.1': 'Gives me a little energy',
    'energy.level.2': 'Gives me a lot of energy',
    's4.energy.continue': 'Continue',
    's5.title': 'Waiting for the room',
    's5.lines.0': 'Five',
    's5.lines.1': 'Six',
    's5.lines.2': 'Seven',
    's5.lines.3': 'Eight',
    's4.reveal.title': 'One more commitment',
    's4.reveal.body': 'Fit it into your week.',
    's4.pace.title': 'How much of your week',
    's4.pace.perDay': '{hours} h on each workday',
    's4.pace.continue': 'Continue',
    's4.confirm': 'Confirm',
    'sheet.setDirect': 'Set directly',
    'sheet.done': 'Done',
    'band.unallocated': 'Unallocated',
    'band.notIncluded': 'Not included',
    'band.notIncludedCount': '{count} not included',
    's1.next': 'Next',
    's1.back': 'Back',
    'intro.multitasking': 'Each hour belongs to one activity.',
    'intro.continue': 'Continue',
    'join.prompt': 'Enter the room code',
    'join.label': 'Room code',
    'join.action': 'Join',
    'join.error.unknown': 'That code does not match a room.',
    'join.error.failed': 'Could not reach the server. Try again.',
    'unit.minutes': 'min',
    'unit.hours': 'h',
    'unit.times': 'times',
    'a11y.decrease': 'Decrease',
    'a11y.increase': 'Increase',
    'options.open': 'Options',
    'options.reset': 'Start over',
    'options.reset.title': 'Start over?',
    'options.reset.body': 'This erases your answers.',
    'options.reset.confirm': 'Start over',
    'options.reset.cancel': 'Cancel',
    'options.reset.failed': 'Could not reach the server. Try again.',
    'options.reset.body.complete': 'This erases your answers and your finished result.',
    's5.title': 'What it cost',
    's5.cuts.row': '{from} h → {to} h',
    's5.noCuts.title': 'Nothing else in your week moved.',
    's5.noCuts.body': 'It takes {hours} hours a week, out of time you had not allocated.',
  },
};
